// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ConcursProtocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Concurs.Networking {

  /// <summary>Holder for reflection information generated from ConcursProtocol.proto</summary>
  public static partial class ConcursProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for ConcursProtocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConcursProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVDb25jdXJzUHJvdG9jb2wucHJvdG8SEmNvbmN1cnMubmV0d29ya2luZyI3",
            "CgVBZG1pbhIKCgJpZBgBIAEoCRIQCgh1c2VybmFtZRgCIAEoCRIQCghwYXNz",
            "d29yZBgDIAEoCSJLCgVQcm9iYRIKCgJpZBgBIAEoCRIQCghkaXN0YW50YRgC",
            "IAEoCRIMCgRzdGlsGAMgASgJEhYKDm5yUGFydGljaXBhbnRpGAQgASgJIkYK",
            "C1BhcnRpY2lwYW50EgoKAmlkGAEgASgJEgwKBG51bWUYAiABKAkSDgoGdmFy",
            "c3RhGAMgASgJEg0KBXByb2JlGAQgASgJIuoCCg5Db25jdXJzUmVxdWVzdBI1",
            "CgR0eXBlGAEgASgOMicuY29uY3Vycy5uZXR3b3JraW5nLkNvbmN1cnNSZXF1",
            "ZXN0LlR5cGUSKgoFYWRtaW4YAiABKAsyGS5jb25jdXJzLm5ldHdvcmtpbmcu",
            "QWRtaW5IABI2CgtwYXJ0aWNpcGFudBgDIAEoCzIfLmNvbmN1cnMubmV0d29y",
            "a2luZy5QYXJ0aWNpcGFudEgAEhEKB2lkUHJvYmEYBCABKAlIABIWCgxzZWFy",
            "Y2hTdHJpbmcYBSABKAlIACKGAQoEVHlwZRILCgdVbmtub3duEAASCQoFTG9n",
            "aW4QARIKCgZMb2dvdXQQAhIMCghHZXRQcm9iZRADEhUKEUNhdXRhUGFydGlj",
            "aXBhbnRpEAQSEgoOQWRkUGFydGljaXBhbnQQBRITCg9HZXRQYXJ0aWNpcGFu",
            "dGkQBhIMCghHZXRQcm9iYRAHQgkKB3BheWxvYWQizQMKD0NvbmN1cnNSZXNw",
            "b25zZRI2CgR0eXBlGAEgASgOMiguY29uY3Vycy5uZXR3b3JraW5nLkNvbmN1",
            "cnNSZXNwb25zZS5UeXBlEg0KBWVycm9yGAIgASgJEigKBXByb2JlGAMgAygL",
            "MhkuY29uY3Vycy5uZXR3b3JraW5nLlByb2JhEjUKDHBhcnRpY2lwYW50aRgE",
            "IAMoCzIfLmNvbmN1cnMubmV0d29ya2luZy5QYXJ0aWNpcGFudBIoCgVwcm9i",
            "YRgFIAEoCzIZLmNvbmN1cnMubmV0d29ya2luZy5Qcm9iYRIoCgVhZG1pbhgG",
            "IAEoCzIZLmNvbmN1cnMubmV0d29ya2luZy5BZG1pbhI0CgtwYXJ0aWNpcGFu",
            "dBgHIAEoCzIfLmNvbmN1cnMubmV0d29ya2luZy5QYXJ0aWNpcGFudCKHAQoE",
            "VHlwZRILCgdVbmtub3duEAASBgoCT2sQARIJCgVFcnJvchACEhQKEEFkZGVk",
            "UGFydGljaXBhbnQQAxIMCghHZXRQcm9iZRAEEhMKD0dldFBhcnRpY2lwYW50",
            "aRAFEgwKCEdldFByb2JhEAYSGAoUU2VhcmNoZWRQYXJ0aWNpcGFudGkQB2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Concurs.Networking.Admin), global::Concurs.Networking.Admin.Parser, new[]{ "Id", "Username", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Concurs.Networking.Proba), global::Concurs.Networking.Proba.Parser, new[]{ "Id", "Distanta", "Stil", "NrParticipanti" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Concurs.Networking.Participant), global::Concurs.Networking.Participant.Parser, new[]{ "Id", "Nume", "Varsta", "Probe" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Concurs.Networking.ConcursRequest), global::Concurs.Networking.ConcursRequest.Parser, new[]{ "Type", "Admin", "Participant", "IdProba", "SearchString" }, new[]{ "Payload" }, new[]{ typeof(global::Concurs.Networking.ConcursRequest.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Concurs.Networking.ConcursResponse), global::Concurs.Networking.ConcursResponse.Parser, new[]{ "Type", "Error", "Probe", "Participanti", "Proba", "Admin", "Participant" }, null, new[]{ typeof(global::Concurs.Networking.ConcursResponse.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Admin : pb::IMessage<Admin>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Admin> _parser = new pb::MessageParser<Admin>(() => new Admin());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Admin> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Concurs.Networking.ConcursProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Admin() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Admin(Admin other) : this() {
      id_ = other.id_;
      username_ = other.username_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Admin Clone() {
      return new Admin(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 2;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 3;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Admin);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Admin other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Username.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Admin other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Username = input.ReadString();
            break;
          }
          case 26: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Proba : pb::IMessage<Proba>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Proba> _parser = new pb::MessageParser<Proba>(() => new Proba());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Proba> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Concurs.Networking.ConcursProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Proba() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Proba(Proba other) : this() {
      id_ = other.id_;
      distanta_ = other.distanta_;
      stil_ = other.stil_;
      nrParticipanti_ = other.nrParticipanti_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Proba Clone() {
      return new Proba(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "distanta" field.</summary>
    public const int DistantaFieldNumber = 2;
    private string distanta_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Distanta {
      get { return distanta_; }
      set {
        distanta_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "stil" field.</summary>
    public const int StilFieldNumber = 3;
    private string stil_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Stil {
      get { return stil_; }
      set {
        stil_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nrParticipanti" field.</summary>
    public const int NrParticipantiFieldNumber = 4;
    private string nrParticipanti_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NrParticipanti {
      get { return nrParticipanti_; }
      set {
        nrParticipanti_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Proba);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Proba other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Distanta != other.Distanta) return false;
      if (Stil != other.Stil) return false;
      if (NrParticipanti != other.NrParticipanti) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Distanta.Length != 0) hash ^= Distanta.GetHashCode();
      if (Stil.Length != 0) hash ^= Stil.GetHashCode();
      if (NrParticipanti.Length != 0) hash ^= NrParticipanti.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Distanta.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Distanta);
      }
      if (Stil.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Stil);
      }
      if (NrParticipanti.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NrParticipanti);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Distanta.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Distanta);
      }
      if (Stil.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Stil);
      }
      if (NrParticipanti.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NrParticipanti);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Distanta.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Distanta);
      }
      if (Stil.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Stil);
      }
      if (NrParticipanti.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NrParticipanti);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Proba other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Distanta.Length != 0) {
        Distanta = other.Distanta;
      }
      if (other.Stil.Length != 0) {
        Stil = other.Stil;
      }
      if (other.NrParticipanti.Length != 0) {
        NrParticipanti = other.NrParticipanti;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Distanta = input.ReadString();
            break;
          }
          case 26: {
            Stil = input.ReadString();
            break;
          }
          case 34: {
            NrParticipanti = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Distanta = input.ReadString();
            break;
          }
          case 26: {
            Stil = input.ReadString();
            break;
          }
          case 34: {
            NrParticipanti = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Participant : pb::IMessage<Participant>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Participant> _parser = new pb::MessageParser<Participant>(() => new Participant());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Participant> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Concurs.Networking.ConcursProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Participant() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Participant(Participant other) : this() {
      id_ = other.id_;
      nume_ = other.nume_;
      varsta_ = other.varsta_;
      probe_ = other.probe_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Participant Clone() {
      return new Participant(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nume" field.</summary>
    public const int NumeFieldNumber = 2;
    private string nume_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nume {
      get { return nume_; }
      set {
        nume_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "varsta" field.</summary>
    public const int VarstaFieldNumber = 3;
    private string varsta_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Varsta {
      get { return varsta_; }
      set {
        varsta_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "probe" field.</summary>
    public const int ProbeFieldNumber = 4;
    private string probe_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Probe {
      get { return probe_; }
      set {
        probe_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Participant);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Participant other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Nume != other.Nume) return false;
      if (Varsta != other.Varsta) return false;
      if (Probe != other.Probe) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Nume.Length != 0) hash ^= Nume.GetHashCode();
      if (Varsta.Length != 0) hash ^= Varsta.GetHashCode();
      if (Probe.Length != 0) hash ^= Probe.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (Varsta.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Varsta);
      }
      if (Probe.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Probe);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Nume.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nume);
      }
      if (Varsta.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Varsta);
      }
      if (Probe.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Probe);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Nume.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nume);
      }
      if (Varsta.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Varsta);
      }
      if (Probe.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Probe);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Participant other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Nume.Length != 0) {
        Nume = other.Nume;
      }
      if (other.Varsta.Length != 0) {
        Varsta = other.Varsta;
      }
      if (other.Probe.Length != 0) {
        Probe = other.Probe;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 26: {
            Varsta = input.ReadString();
            break;
          }
          case 34: {
            Probe = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Nume = input.ReadString();
            break;
          }
          case 26: {
            Varsta = input.ReadString();
            break;
          }
          case 34: {
            Probe = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ConcursRequest : pb::IMessage<ConcursRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConcursRequest> _parser = new pb::MessageParser<ConcursRequest>(() => new ConcursRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ConcursRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Concurs.Networking.ConcursProtocolReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConcursRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConcursRequest(ConcursRequest other) : this() {
      type_ = other.type_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.Admin:
          Admin = other.Admin.Clone();
          break;
        case PayloadOneofCase.Participant:
          Participant = other.Participant.Clone();
          break;
        case PayloadOneofCase.IdProba:
          IdProba = other.IdProba;
          break;
        case PayloadOneofCase.SearchString:
          SearchString = other.SearchString;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConcursRequest Clone() {
      return new ConcursRequest(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Concurs.Networking.ConcursRequest.Types.Type type_ = global::Concurs.Networking.ConcursRequest.Types.Type.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Concurs.Networking.ConcursRequest.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "admin" field.</summary>
    public const int AdminFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Concurs.Networking.Admin Admin {
      get { return payloadCase_ == PayloadOneofCase.Admin ? (global::Concurs.Networking.Admin) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Admin;
      }
    }

    /// <summary>Field number for the "participant" field.</summary>
    public const int ParticipantFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Concurs.Networking.Participant Participant {
      get { return payloadCase_ == PayloadOneofCase.Participant ? (global::Concurs.Networking.Participant) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Participant;
      }
    }

    /// <summary>Field number for the "idProba" field.</summary>
    public const int IdProbaFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdProba {
      get { return payloadCase_ == PayloadOneofCase.IdProba ? (string) payload_ : ""; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        payloadCase_ = PayloadOneofCase.IdProba;
      }
    }

    /// <summary>Field number for the "searchString" field.</summary>
    public const int SearchStringFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SearchString {
      get { return payloadCase_ == PayloadOneofCase.SearchString ? (string) payload_ : ""; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        payloadCase_ = PayloadOneofCase.SearchString;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      Admin = 2,
      Participant = 3,
      IdProba = 4,
      SearchString = 5,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ConcursRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ConcursRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Admin, other.Admin)) return false;
      if (!object.Equals(Participant, other.Participant)) return false;
      if (IdProba != other.IdProba) return false;
      if (SearchString != other.SearchString) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Concurs.Networking.ConcursRequest.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Admin) hash ^= Admin.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Participant) hash ^= Participant.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.IdProba) hash ^= IdProba.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.SearchString) hash ^= SearchString.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Concurs.Networking.ConcursRequest.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Admin) {
        output.WriteRawTag(18);
        output.WriteMessage(Admin);
      }
      if (payloadCase_ == PayloadOneofCase.Participant) {
        output.WriteRawTag(26);
        output.WriteMessage(Participant);
      }
      if (payloadCase_ == PayloadOneofCase.IdProba) {
        output.WriteRawTag(34);
        output.WriteString(IdProba);
      }
      if (payloadCase_ == PayloadOneofCase.SearchString) {
        output.WriteRawTag(42);
        output.WriteString(SearchString);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Concurs.Networking.ConcursRequest.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Admin) {
        output.WriteRawTag(18);
        output.WriteMessage(Admin);
      }
      if (payloadCase_ == PayloadOneofCase.Participant) {
        output.WriteRawTag(26);
        output.WriteMessage(Participant);
      }
      if (payloadCase_ == PayloadOneofCase.IdProba) {
        output.WriteRawTag(34);
        output.WriteString(IdProba);
      }
      if (payloadCase_ == PayloadOneofCase.SearchString) {
        output.WriteRawTag(42);
        output.WriteString(SearchString);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Concurs.Networking.ConcursRequest.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Admin) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Admin);
      }
      if (payloadCase_ == PayloadOneofCase.Participant) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participant);
      }
      if (payloadCase_ == PayloadOneofCase.IdProba) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdProba);
      }
      if (payloadCase_ == PayloadOneofCase.SearchString) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SearchString);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ConcursRequest other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Concurs.Networking.ConcursRequest.Types.Type.Unknown) {
        Type = other.Type;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.Admin:
          if (Admin == null) {
            Admin = new global::Concurs.Networking.Admin();
          }
          Admin.MergeFrom(other.Admin);
          break;
        case PayloadOneofCase.Participant:
          if (Participant == null) {
            Participant = new global::Concurs.Networking.Participant();
          }
          Participant.MergeFrom(other.Participant);
          break;
        case PayloadOneofCase.IdProba:
          IdProba = other.IdProba;
          break;
        case PayloadOneofCase.SearchString:
          SearchString = other.SearchString;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Concurs.Networking.ConcursRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Concurs.Networking.Admin subBuilder = new global::Concurs.Networking.Admin();
            if (payloadCase_ == PayloadOneofCase.Admin) {
              subBuilder.MergeFrom(Admin);
            }
            input.ReadMessage(subBuilder);
            Admin = subBuilder;
            break;
          }
          case 26: {
            global::Concurs.Networking.Participant subBuilder = new global::Concurs.Networking.Participant();
            if (payloadCase_ == PayloadOneofCase.Participant) {
              subBuilder.MergeFrom(Participant);
            }
            input.ReadMessage(subBuilder);
            Participant = subBuilder;
            break;
          }
          case 34: {
            IdProba = input.ReadString();
            break;
          }
          case 42: {
            SearchString = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Concurs.Networking.ConcursRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Concurs.Networking.Admin subBuilder = new global::Concurs.Networking.Admin();
            if (payloadCase_ == PayloadOneofCase.Admin) {
              subBuilder.MergeFrom(Admin);
            }
            input.ReadMessage(subBuilder);
            Admin = subBuilder;
            break;
          }
          case 26: {
            global::Concurs.Networking.Participant subBuilder = new global::Concurs.Networking.Participant();
            if (payloadCase_ == PayloadOneofCase.Participant) {
              subBuilder.MergeFrom(Participant);
            }
            input.ReadMessage(subBuilder);
            Participant = subBuilder;
            break;
          }
          case 34: {
            IdProba = input.ReadString();
            break;
          }
          case 42: {
            SearchString = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ConcursRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Login")] Login = 1,
        [pbr::OriginalName("Logout")] Logout = 2,
        [pbr::OriginalName("GetProbe")] GetProbe = 3,
        [pbr::OriginalName("CautaParticipanti")] CautaParticipanti = 4,
        [pbr::OriginalName("AddParticipant")] AddParticipant = 5,
        [pbr::OriginalName("GetParticipanti")] GetParticipanti = 6,
        [pbr::OriginalName("GetProba")] GetProba = 7,
      }

    }
    #endregion

  }

  public sealed partial class ConcursResponse : pb::IMessage<ConcursResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ConcursResponse> _parser = new pb::MessageParser<ConcursResponse>(() => new ConcursResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ConcursResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Concurs.Networking.ConcursProtocolReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConcursResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConcursResponse(ConcursResponse other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      probe_ = other.probe_.Clone();
      participanti_ = other.participanti_.Clone();
      proba_ = other.proba_ != null ? other.proba_.Clone() : null;
      admin_ = other.admin_ != null ? other.admin_.Clone() : null;
      participant_ = other.participant_ != null ? other.participant_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConcursResponse Clone() {
      return new ConcursResponse(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Concurs.Networking.ConcursResponse.Types.Type type_ = global::Concurs.Networking.ConcursResponse.Types.Type.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Concurs.Networking.ConcursResponse.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "probe" field.</summary>
    public const int ProbeFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Concurs.Networking.Proba> _repeated_probe_codec
        = pb::FieldCodec.ForMessage(26, global::Concurs.Networking.Proba.Parser);
    private readonly pbc::RepeatedField<global::Concurs.Networking.Proba> probe_ = new pbc::RepeatedField<global::Concurs.Networking.Proba>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Concurs.Networking.Proba> Probe {
      get { return probe_; }
    }

    /// <summary>Field number for the "participanti" field.</summary>
    public const int ParticipantiFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Concurs.Networking.Participant> _repeated_participanti_codec
        = pb::FieldCodec.ForMessage(34, global::Concurs.Networking.Participant.Parser);
    private readonly pbc::RepeatedField<global::Concurs.Networking.Participant> participanti_ = new pbc::RepeatedField<global::Concurs.Networking.Participant>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Concurs.Networking.Participant> Participanti {
      get { return participanti_; }
    }

    /// <summary>Field number for the "proba" field.</summary>
    public const int ProbaFieldNumber = 5;
    private global::Concurs.Networking.Proba proba_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Concurs.Networking.Proba Proba {
      get { return proba_; }
      set {
        proba_ = value;
      }
    }

    /// <summary>Field number for the "admin" field.</summary>
    public const int AdminFieldNumber = 6;
    private global::Concurs.Networking.Admin admin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Concurs.Networking.Admin Admin {
      get { return admin_; }
      set {
        admin_ = value;
      }
    }

    /// <summary>Field number for the "participant" field.</summary>
    public const int ParticipantFieldNumber = 7;
    private global::Concurs.Networking.Participant participant_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Concurs.Networking.Participant Participant {
      get { return participant_; }
      set {
        participant_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ConcursResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ConcursResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if(!probe_.Equals(other.probe_)) return false;
      if(!participanti_.Equals(other.participanti_)) return false;
      if (!object.Equals(Proba, other.Proba)) return false;
      if (!object.Equals(Admin, other.Admin)) return false;
      if (!object.Equals(Participant, other.Participant)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Concurs.Networking.ConcursResponse.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      hash ^= probe_.GetHashCode();
      hash ^= participanti_.GetHashCode();
      if (proba_ != null) hash ^= Proba.GetHashCode();
      if (admin_ != null) hash ^= Admin.GetHashCode();
      if (participant_ != null) hash ^= Participant.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Concurs.Networking.ConcursResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      probe_.WriteTo(output, _repeated_probe_codec);
      participanti_.WriteTo(output, _repeated_participanti_codec);
      if (proba_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Proba);
      }
      if (admin_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Admin);
      }
      if (participant_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Participant);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Concurs.Networking.ConcursResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      probe_.WriteTo(ref output, _repeated_probe_codec);
      participanti_.WriteTo(ref output, _repeated_participanti_codec);
      if (proba_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Proba);
      }
      if (admin_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Admin);
      }
      if (participant_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Participant);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Concurs.Networking.ConcursResponse.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      size += probe_.CalculateSize(_repeated_probe_codec);
      size += participanti_.CalculateSize(_repeated_participanti_codec);
      if (proba_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Proba);
      }
      if (admin_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Admin);
      }
      if (participant_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Participant);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ConcursResponse other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Concurs.Networking.ConcursResponse.Types.Type.Unknown) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      probe_.Add(other.probe_);
      participanti_.Add(other.participanti_);
      if (other.proba_ != null) {
        if (proba_ == null) {
          Proba = new global::Concurs.Networking.Proba();
        }
        Proba.MergeFrom(other.Proba);
      }
      if (other.admin_ != null) {
        if (admin_ == null) {
          Admin = new global::Concurs.Networking.Admin();
        }
        Admin.MergeFrom(other.Admin);
      }
      if (other.participant_ != null) {
        if (participant_ == null) {
          Participant = new global::Concurs.Networking.Participant();
        }
        Participant.MergeFrom(other.Participant);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Concurs.Networking.ConcursResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            probe_.AddEntriesFrom(input, _repeated_probe_codec);
            break;
          }
          case 34: {
            participanti_.AddEntriesFrom(input, _repeated_participanti_codec);
            break;
          }
          case 42: {
            if (proba_ == null) {
              Proba = new global::Concurs.Networking.Proba();
            }
            input.ReadMessage(Proba);
            break;
          }
          case 50: {
            if (admin_ == null) {
              Admin = new global::Concurs.Networking.Admin();
            }
            input.ReadMessage(Admin);
            break;
          }
          case 58: {
            if (participant_ == null) {
              Participant = new global::Concurs.Networking.Participant();
            }
            input.ReadMessage(Participant);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Concurs.Networking.ConcursResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            probe_.AddEntriesFrom(ref input, _repeated_probe_codec);
            break;
          }
          case 34: {
            participanti_.AddEntriesFrom(ref input, _repeated_participanti_codec);
            break;
          }
          case 42: {
            if (proba_ == null) {
              Proba = new global::Concurs.Networking.Proba();
            }
            input.ReadMessage(Proba);
            break;
          }
          case 50: {
            if (admin_ == null) {
              Admin = new global::Concurs.Networking.Admin();
            }
            input.ReadMessage(Admin);
            break;
          }
          case 58: {
            if (participant_ == null) {
              Participant = new global::Concurs.Networking.Participant();
            }
            input.ReadMessage(Participant);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ConcursResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Ok")] Ok = 1,
        [pbr::OriginalName("Error")] Error = 2,
        [pbr::OriginalName("AddedParticipant")] AddedParticipant = 3,
        [pbr::OriginalName("GetProbe")] GetProbe = 4,
        [pbr::OriginalName("GetParticipanti")] GetParticipanti = 5,
        [pbr::OriginalName("GetProba")] GetProba = 6,
        [pbr::OriginalName("SearchedParticipanti")] SearchedParticipanti = 7,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
